fix = true
line-length = 88
exclude = [
    "build",
    "dist",
    "docs",
    "examples",
    "scripts",
    "tests",
    "third_party",
    "venv",
    "labs/utils/cma.py",
]
target-version = "py310"

extend-include = ["*.ipynb"]

[format]
preview = true

[lint]
fixable = ["ALL"]

[lint.pydocstyle]
convention = "google"